import SwiftUI

struct LogsView: View {
    @ObservedObject var logger: Logger
    @Environment(\.dismiss) private var dismiss

    private let logsURL: URL = {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("lara.log")
    }()

    var body: some View {
        NavigationStack {
            ZStack {
                LaraPalette.background.ignoresSafeArea()

                VStack(spacing: 12) {
                    ScrollViewReader { proxy in
                        ScrollView(showsIndicators: false) {
                            VStack(alignment: .leading, spacing: 4) {
                                ForEach(Array(logger.logs.enumerated()), id: \.offset) { index, line in
                                    Text(line)
                                        .font(.laraMono)
                                        .foregroundStyle(LaraPalette.primary.opacity(0.92))
                                        .textSelection(.enabled)
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                        .id(index)
                                }

                                if logger.logs.isEmpty {
                                    VStack(spacing: 10) {
                                        Image(systemName: "terminal")
                                            .font(.system(size: 28, weight: .light))
                                            .foregroundStyle(LaraPalette.secondary)
                                        Text("No logs yet")
                                            .font(.laraBodySemibold)
                                            .foregroundStyle(LaraPalette.primary)
                                        Text("Logs generated by Lara will appear here.")
                                            .font(.laraCaption)
                                            .foregroundStyle(LaraPalette.secondary)
                                            .multilineTextAlignment(.center)
                                    }
                                    .frame(maxWidth: .infinity)
                                    .padding(.top, 100)
                                }
                            }
                            .padding(14)
                        }
                        .background(LaraPalette.terminal)
                        .clipShape(RoundedRectangle(cornerRadius: 18, style: .continuous))
                        .overlay(
                            RoundedRectangle(cornerRadius: 18, style: .continuous)
                                .stroke(Color.white.opacity(0.06), lineWidth: 0.5)
                        )
                        .padding(.horizontal, 12)
                        .onChange(of: logger.logs.count) { count in
                            guard count > 0 else { return }
                            withAnimation(.easeOut(duration: 0.15)) {
                                proxy.scrollTo(count - 1, anchor: .bottom)
                            }
                        }
                    }

                    HStack(spacing: 8) {
                        Button {
                            UIPasteboard.general.string = logger.logs.joined(separator: "\n\n")
                            UIImpactFeedbackGenerator(style: .medium).impactOccurred()
                        } label: {
                            Label("Copy", systemImage: "doc.on.doc")
                        }
                        .buttonStyle(.bordered)
                        .tint(LaraPalette.accent)

                        ShareLink(item: logsURL) {
                            Label("Share", systemImage: "square.and.arrow.up")
                        }
                        .buttonStyle(.bordered)
                        .tint(LaraPalette.accent)

                        Spacer()

                        Button(role: .destructive) {
                            logger.clear()
                        } label: {
                            Label("Clear", systemImage: "trash")
                        }
                        .buttonStyle(.bordered)
                    }
                    .padding(.horizontal, 12)
                }
                .padding(.top, 4)
            }
            .navigationTitle("Logs")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Text("\(logger.logs.count) lines")
                        .font(.system(size: 11, design: .monospaced))
                        .foregroundStyle(LaraPalette.secondary)
                }
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") { dismiss() }
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundStyle(LaraPalette.accent)
                }
            }
        }
        .presentationDetents([.medium, .large])
        .presentationDragIndicator(.visible)
        .preferredColorScheme(.dark)
    }
}